/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Product_Controller;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Kephas73
 */
public class frmHome extends javax.swing.JFrame {

    /**
     * Creates new form NewMDIApplication
     */
    public frmHome() {
        initComponents();
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        helpMenu = new javax.swing.JMenu();
        bttLogin = new javax.swing.JMenuItem();
        bttLogout = new javax.swing.JMenuItem();
        bttRegister = new javax.swing.JMenuItem();
        bttChangepw = new javax.swing.JMenuItem();
        bttAuthorization = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        bttPay = new javax.swing.JMenuItem();
        bttProduct = new javax.swing.JMenuItem();
        bttCustomer = new javax.swing.JMenuItem();
        bttEmployee = new javax.swing.JMenuItem();
        bttPromote = new javax.swing.JMenuItem();
        bttAttendance = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        bttAuthor = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        bttGuide = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("VIETFRUIT");
        setResizable(false);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Copyrights © 2019- nguyencattien.qb@gmail.com");

        helpMenu.setMnemonic('h');
        helpMenu.setText("Home");

        bttLogin.setText("Login");
        bttLogin.setName("gg"); // NOI18N
        bttLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttLoginActionPerformed(evt);
            }
        });
        helpMenu.add(bttLogin);

        bttLogout.setText("Logout");
        helpMenu.add(bttLogout);

        bttRegister.setText("Register");
        helpMenu.add(bttRegister);

        bttChangepw.setText("Change Password");
        bttChangepw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttChangepwActionPerformed(evt);
            }
        });
        helpMenu.add(bttChangepw);

        bttAuthorization.setText("Account authorization");
        helpMenu.add(bttAuthorization);

        menuBar.add(helpMenu);

        jMenu1.setText("Utilities");

        bttPay.setText("Pay");
        bttPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttPayActionPerformed(evt);
            }
        });
        jMenu1.add(bttPay);

        bttProduct.setText("Product");
        bttProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttProductActionPerformed(evt);
            }
        });
        jMenu1.add(bttProduct);

        bttCustomer.setText("Customer");
        bttCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttCustomerActionPerformed(evt);
            }
        });
        jMenu1.add(bttCustomer);

        bttEmployee.setText("Employee");
        bttEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttEmployeeActionPerformed(evt);
            }
        });
        jMenu1.add(bttEmployee);

        bttPromote.setText("Promote");
        jMenu1.add(bttPromote);

        bttAttendance.setText("Attendance");
        jMenu1.add(bttAttendance);

        menuBar.add(jMenu1);

        jMenu2.setText("Setting");
        menuBar.add(jMenu2);

        bttAuthor.setText("About");

        jMenuItem11.setText("Author");
        bttAuthor.add(jMenuItem11);

        bttGuide.setText("Guide");
        bttAuthor.add(bttGuide);

        menuBar.add(bttAuthor);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDesktopPane1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1191, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bttLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttLoginActionPerformed
        // TODO add your handling code here:
        frmLogin frm = new frmLogin();
        jDesktopPane1.add(frm);
        frm.setResizable(true);
        frm.setVisible(true);
        
    }//GEN-LAST:event_bttLoginActionPerformed

    private void bttChangepwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttChangepwActionPerformed
        // TODO add your handling code here:
        frmChangepw frm=new frmChangepw();
         jDesktopPane1.add(frm);
        frm.setResizable(true);
        frm.setVisible(true);
    }//GEN-LAST:event_bttChangepwActionPerformed

    private void bttProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttProductActionPerformed
        try {
            // TODO add your handling code here:
            frmProduct frm= new  frmProduct();
            jDesktopPane1.add(frm);
            frm.setResizable(true);
            frm.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(frmHome.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bttProductActionPerformed

    private void bttCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttCustomerActionPerformed
        try {
            frmCustomer frm= new  frmCustomer();
            jDesktopPane1.add(frm);
            frm.setResizable(true);
            frm.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(frmHome.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bttCustomerActionPerformed

    private void bttEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttEmployeeActionPerformed
        try {
            frmEmployee frm= new  frmEmployee();
            jDesktopPane1.add(frm);
            frm.setResizable(true);
            frm.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(frmHome.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bttEmployeeActionPerformed

    private void bttPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttPayActionPerformed
        try {
            frmPay frm= new  frmPay();
            jDesktopPane1.add(frm);
            frm.setResizable(true);
            frm.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(frmHome.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bttPayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold> 
        /* Create and display the form */      
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmHome().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem bttAttendance;
    private javax.swing.JMenu bttAuthor;
    private javax.swing.JMenuItem bttAuthorization;
    private javax.swing.JMenuItem bttChangepw;
    private javax.swing.JMenuItem bttCustomer;
    private javax.swing.JMenuItem bttEmployee;
    private javax.swing.JMenuItem bttGuide;
    private javax.swing.JMenuItem bttLogin;
    private javax.swing.JMenuItem bttLogout;
    private javax.swing.JMenuItem bttPay;
    private javax.swing.JMenuItem bttProduct;
    private javax.swing.JMenuItem bttPromote;
    private javax.swing.JMenuItem bttRegister;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
