/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Product_Controller;
import Model.Product_Model;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kephas73
 */
public class frmProduct extends javax.swing.JInternalFrame {

      Product_Controller product_Controller= new  Product_Controller();
      Product_Model product_Model= new Product_Model();
      boolean Status =false;
      
       //private JPanel panel;
    /**
     * Creates new form frmProduct
     */
    public frmProduct() throws SQLException {
        initComponents();
       List_Product();
        Status_txt(false);
        Status_bt(true);
    }

    public void Status_txt(boolean st )
    {
        // txt_Mincode.enable(st);
        txt_name.setEnabled(st);
        txt_weight.setEnabled(st);
        txt_price_in.setEnabled(st);
        txt_price_out.setEnabled(st);
        txt_Pdate.setEnabled(st);
        txt_Edate.setEnabled(st);
        txt_Supplier.setEnabled(st);
        txt_Origin.setEnabled(st);
    }
    public void Remove_txt()
    {
        
        txt_name.setText("");
        txt_weight.setText("");
        txt_price_in.setText("");
        txt_price_out.setText("");
        txt_Supplier.setText("");
        txt_Origin.setText("");
        
    }
    public void Status_bt(boolean st)
    {
        btt_Insert.setEnabled(st);
        btt_Update.setEnabled(st);
        btt_Delete.setEnabled(st);
        btt_Save.setEnabled(!st);
        btt_Back.setEnabled(!st);
    }
    public void List_Product() throws SQLException{
      
        ResultSet rs=product_Controller.List_Product();
         String[] arr = {"Min code", "Name","Weight","Price(in)","Price(out)","Packaging","Expiration","Supplier","Origin"};
        DefaultTableModel tableModel = new DefaultTableModel(arr, 0);
          tb_ListProduct.setModel(tableModel);
         try {
            while (rs.next()) {
                 Vector vt= new Vector();
                 vt.add(rs.getString("MA_SAN_PHAM"));
                  vt.add(rs.getString("TEN_SAN_PHAM"));
                   vt.add(rs.getFloat("KHOI_LUONG_NHAP"));
                    vt.add(rs.getFloat("GIA_NHAP_VAO"));
                    vt.add(rs.getFloat("GIA_BAN_RA")); 
                     vt.add(rs.getDate("NGAY_DONG_GOI"));
                     vt.add(rs.getDate("NGAY_HET_HAN"));
                    vt.add(rs.getString("NHA_CUNG_CAP"));
                    vt.add(rs.getString("NOI_XUAT_XU"));
                tableModel.addRow(vt);
            }
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_ListProduct = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btt_Insert = new javax.swing.JButton();
        btt_Update = new javax.swing.JButton();
        btt_Delete = new javax.swing.JButton();
        btt_Save = new javax.swing.JButton();
        btt_Back = new javax.swing.JButton();
        txt_Mincode = new javax.swing.JTextField();
        txt_name = new javax.swing.JTextField();
        txt_weight = new javax.swing.JTextField();
        txt_price_in = new javax.swing.JTextField();
        txt_price_out = new javax.swing.JTextField();
        txt_Pdate = new com.toedter.calendar.JDateChooser();
        txt_Edate = new com.toedter.calendar.JDateChooser();
        txt_Supplier = new javax.swing.JTextField();
        txt_Origin = new javax.swing.JTextField();
        txt_Search = new javax.swing.JTextField();
        cm_Search = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        bttSearch = new javax.swing.JButton();

        setClosable(true);
        setTitle("Product Management");
        setPreferredSize(new java.awt.Dimension(1191, 590));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " List of product", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(51, 51, 255))); // NOI18N

        tb_ListProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Min code", "Name", "Net weight", "Price (in)", "Price (out)", "Packaging date", "Expiration date", "Supplier", "Origin"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tb_ListProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_ListProductMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_ListProduct);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Properties", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(51, 51, 255))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Min code:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Name:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Price (in):");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Net weight:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Price (out):");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Origin:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Expiration date:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Supplier:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Packaging date:");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Control", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(51, 51, 255))); // NOI18N

        btt_Insert.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btt_Insert.setText("Insert");
        btt_Insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt_InsertActionPerformed(evt);
            }
        });

        btt_Update.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btt_Update.setText("Update");
        btt_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt_UpdateActionPerformed(evt);
            }
        });

        btt_Delete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btt_Delete.setText("Delete");
        btt_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt_DeleteActionPerformed(evt);
            }
        });

        btt_Save.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btt_Save.setText("Save");
        btt_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt_SaveActionPerformed(evt);
            }
        });

        btt_Back.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btt_Back.setText("Back");
        btt_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt_BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btt_Insert)
                .addGap(18, 18, 18)
                .addComponent(btt_Update)
                .addGap(18, 18, 18)
                .addComponent(btt_Delete)
                .addGap(18, 18, 18)
                .addComponent(btt_Save)
                .addGap(18, 18, 18)
                .addComponent(btt_Back)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btt_Insert)
                    .addComponent(btt_Update)
                    .addComponent(btt_Delete)
                    .addComponent(btt_Save)
                    .addComponent(btt_Back))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        txt_Mincode.setEnabled(false);

        txt_Pdate.setDateFormatString("dd-MM-yyyy");

        txt_Edate.setDateFormatString("dd-MM-yyyy");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_Mincode, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_price_out, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addGap(3, 3, 3)
                                                .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txt_price_in, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txt_weight, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel6))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_Pdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_Edate, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                            .addComponent(txt_Supplier, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_Origin, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel9)
                        .addComponent(txt_Mincode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_Pdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel7)
                        .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_Edate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(txt_weight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Supplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(txt_price_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Origin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_price_out, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cm_Search.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Min code", "Name" }));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Search:");

        bttSearch.setIcon(new javax.swing.ImageIcon("C:\\Users\\nguye\\Downloads\\icons8-search-26.png")); // NOI18N
        bttSearch.setLabel("");
        bttSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(cm_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bttSearch)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(cm_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bttSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jPanel2.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tb_ListProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_ListProductMouseClicked
        // TODO add your handling code here:
         int index = tb_ListProduct.getSelectedRow();
        txt_Mincode.setText(tb_ListProduct.getValueAt(index, 0).toString());
        txt_name.setText(tb_ListProduct.getValueAt(index, 1).toString());
        txt_weight.setText(tb_ListProduct.getValueAt(index, 2).toString());
        txt_price_in.setText(tb_ListProduct.getValueAt(index, 3).toString());
        txt_price_out.setText(tb_ListProduct.getValueAt(index, 4).toString());
        txt_Pdate.setDate((Date)tb_ListProduct.getValueAt(index, 5));
        txt_Edate.setDate((Date)tb_ListProduct.getValueAt(index, 6));
        txt_Supplier.setText(tb_ListProduct.getValueAt(index, 7).toString());
        txt_Origin.setText(tb_ListProduct.getValueAt(index, 8).toString());
               
          
              
          
    }//GEN-LAST:event_tb_ListProductMouseClicked

    private void btt_InsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt_InsertActionPerformed
        // TODO add your handling code here:
        Status_txt(true);
        Status_bt(false);
        Remove_txt();
        txt_Mincode.setText(product_Controller.Auto_Increment_Mincode());
        Status=true;
        
    }//GEN-LAST:event_btt_InsertActionPerformed

    private void btt_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt_BackActionPerformed
        // TODO add your handling code here:
        
          try {
              
              List_Product();
              Status_txt(false);
              Status_bt(true);
              Remove_txt(); 
          } catch (SQLException ex) {
              Logger.getLogger(frmProduct.class.getName()).log(Level.SEVERE, null, ex);
          }
         
    }//GEN-LAST:event_btt_BackActionPerformed

    private void btt_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt_DeleteActionPerformed
        // TODO add your handling code here:
        int window = JOptionPane.showConfirmDialog(
            null, 
            "Do you want to delete the product", 
            "Notification", 
            JOptionPane.YES_NO_OPTION);
        if(window == JOptionPane.YES_OPTION)
        {
            try {
                product_Model.setMincode(txt_Mincode.getText());
                product_Controller.Delete_Product(product_Model);
                JOptionPane.showMessageDialog(null,"Successfully deleted!");
                List_Product();
                Status_txt(false);
                Status_bt(true);
            } catch (SQLException ex) {
                Logger.getLogger(frmProduct.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
             
    }//GEN-LAST:event_btt_DeleteActionPerformed

    private void btt_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt_UpdateActionPerformed
        // TODO add your handling code here:
        Status_txt(true);
        Status_bt(false);
        Status=false;
    }//GEN-LAST:event_btt_UpdateActionPerformed

    private void btt_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt_SaveActionPerformed
          try {
              // TODO add your handling code here:
                //SimpleDateFormat fm= new SimpleDateFormat("dd-MM-yyyy");
               String Packaging = DateFormat.getDateInstance().format(txt_Pdate.getDate());
               String Expiration = DateFormat.getDateInstance().format(txt_Edate.getDate());
              product_Model.setMincode(txt_Mincode.getText());
              product_Model.setName(txt_name.getText());
              product_Model.setWeight(Float.valueOf(txt_weight.getText()));
              product_Model.setPrice_in(Float.valueOf(txt_price_in.getText()));
              product_Model.setPrice_out(Float.valueOf(txt_price_out.getText()));
              product_Model.setPackaging(Packaging);
            product_Model.setExpiration(Expiration);
              product_Model.setSupplier(txt_Supplier.getText());
              product_Model.setOrigin(txt_Origin.getText());
              product_Model.setImage("NULL"); 
              if(Status==true)
              {
                  product_Controller.Add_Product(product_Model);
                    JOptionPane.showMessageDialog(null,"Successfully add!");
                  
              }
              else{
                  product_Controller.Update_Product(product_Model);
                    JOptionPane.showMessageDialog(null,"Successfully update!");
              }
              
              List_Product();
              Status_txt(false);
              Status_bt(true);
              Remove_txt(); 
          } catch (SQLException ex) {
              Logger.getLogger(frmProduct.class.getName()).log(Level.SEVERE, null, ex);
          }
        
    }//GEN-LAST:event_btt_SaveActionPerformed

    private void bttSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttSearchActionPerformed
        // TODO add your handling code here:
        ResultSet rs = null;
        if(cm_Search.getSelectedItem().toString()=="Name")
        {
              rs=product_Controller.Search_Name(txt_Search.getText());
        }
        else
        {
              rs=product_Controller.Search_Mincode(txt_Search.getText());
        }
         String[] arr = {"Min code", "Name","Weight","Price(in)","Price(out)","Packaging","Expiration","Supplier","Origin"};
        DefaultTableModel tableModel = new DefaultTableModel(arr, 0);
          tb_ListProduct.setModel(tableModel);
         try {
            while (rs.next()) {
                 Vector vt= new Vector();
                 vt.add(rs.getString("MA_SAN_PHAM"));
                  vt.add(rs.getString("TEN_SAN_PHAM"));
                   vt.add(rs.getFloat("KHOI_LUONG_NHAP"));
                    vt.add(rs.getFloat("GIA_NHAP_VAO"));
                    vt.add(rs.getFloat("GIA_BAN_RA")); 
                     vt.add(rs.getDate("NGAY_DONG_GOI"));
                     vt.add(rs.getDate("NGAY_HET_HAN"));
                    vt.add(rs.getString("NHA_CUNG_CAP"));
                    vt.add(rs.getString("NOI_XUAT_XU"));
                tableModel.addRow(vt);
            }
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }
        
    }//GEN-LAST:event_bttSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttSearch;
    private javax.swing.JButton btt_Back;
    private javax.swing.JButton btt_Delete;
    private javax.swing.JButton btt_Insert;
    private javax.swing.JButton btt_Save;
    private javax.swing.JButton btt_Update;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox cm_Search;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_ListProduct;
    private com.toedter.calendar.JDateChooser txt_Edate;
    private javax.swing.JTextField txt_Mincode;
    private javax.swing.JTextField txt_Origin;
    private com.toedter.calendar.JDateChooser txt_Pdate;
    private javax.swing.JTextField txt_Search;
    private javax.swing.JTextField txt_Supplier;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_price_in;
    private javax.swing.JTextField txt_price_out;
    private javax.swing.JTextField txt_weight;
    // End of variables declaration//GEN-END:variables
}
