/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Customer_Controller;
import Controller.Employee_Controller;
import Controller.Invoice_Controller;
import Controller.Invoice_details_Controller;
import Controller.Product_Controller;
import Model.Customer_Model;
import Model.Invoice_Model;
import Model.Invoice_details_Model;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kephas73
 */
public class frmPay extends javax.swing.JInternalFrame {
    Customer_Controller customer_Controller= new  Customer_Controller();
    Product_Controller product_Controller= new  Product_Controller();
    Employee_Controller employee_Controller= new  Employee_Controller();
    Invoice_Controller invoice_Controller= new Invoice_Controller();
    Invoice_details_Controller invoice_details_Controller = new Invoice_details_Controller();
    Customer_Model customer_Model= new  Customer_Model();
    Invoice_Model invoice_Model= new Invoice_Model();
    Invoice_details_Model invoice_details_Model= new Invoice_details_Model();
    
    /**
     * Creates new form frmPay
     */
    public frmPay() throws SQLException {
        initComponents();
        List_Product();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
     public void List_Product() throws SQLException{
      
        ResultSet rs=product_Controller.List_Product();
         String[] arr = {"Min code", "Name","Price"};
        DefaultTableModel tableModel = new DefaultTableModel(arr, 0);
          tb_ListProduct.setModel(tableModel);
         try {
            while (rs.next()) {
                 Vector vt= new Vector();
                 vt.add(rs.getString("MA_SAN_PHAM"));
                  vt.add(rs.getString("TEN_SAN_PHAM"));
                   vt.add(rs.getFloat("GIA_BAN_RA"));
                tableModel.addRow(vt);
            }
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }
    }
     
     boolean Check_Product(String data)
     {
         boolean TF=false;
        int rowCount=tb_ListCart.getRowCount();
         for(int i=0;i<rowCount;i++)
                {
                    if(tb_ListCart.getValueAt(i,0).toString().compareTo(data)==0)
                    {
                        TF=true;
                    }
                }
         return  TF;
     }
     public float Sum()
     {
         float cash=0;
         int rowCount=tb_ListCart.getRowCount();
         if(rowCount==0)
         {
             cash=0;
         }
         else{
             for(int i=0;i<rowCount;i++)
                {
                   cash=cash+Float.valueOf(tb_ListCart.getValueAt(i, 4).toString());
                }          
         } 
         return cash;
     }
     public int Bonus()
     {
        int bonus = 0;
        float sum=Sum();
        if (sum >= 50000 & sum < 100000)
        {
            bonus = 5;
        }
        if (sum >= 100000 & sum < 200000)
        {
            bonus=10;
        }
        if (sum >= 200000)
        {
            bonus=30;
        }
        return bonus;
     }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        cm_Search = new javax.swing.JComboBox();
        txt_Search = new javax.swing.JTextField();
        bttSearch = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_ListProduct = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txt_weight = new javax.swing.JTextField();
        bttBuy = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_ListCart = new javax.swing.JTable();
        bttDelete = new javax.swing.JButton();
        bttPay = new javax.swing.JButton();
        lb_sun = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lb_point = new javax.swing.JLabel();
        txt_minCodeC = new javax.swing.JTextField();
        txt_name = new javax.swing.JTextField();
        txt_point = new javax.swing.JTextField();
        txt_bill = new javax.swing.JTextField();
        txt_cashier = new javax.swing.JTextField();
        txt_minCodeE = new javax.swing.JTextField();
        bttnewInvoice = new javax.swing.JButton();

        setClosable(true);
        setTitle("Pay");
        setPreferredSize(new java.awt.Dimension(1191, 590));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Search:");

        cm_Search.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Min code", "Name" }));

        bttSearch.setIcon(new javax.swing.ImageIcon("C:\\Users\\nguye\\Downloads\\icons8-search-26.png")); // NOI18N
        bttSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttSearchActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " List of product", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(51, 51, 255))); // NOI18N

        tb_ListProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Min code", "Name", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tb_ListProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_ListProductMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_ListProduct);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Weight:");

        bttBuy.setText("Buy");
        bttBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttBuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txt_weight, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(bttBuy))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_weight)
                    .addComponent(bttBuy))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cart", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(51, 51, 255))); // NOI18N

        tb_ListCart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Min code", "Name", "Price", "Weight", "Cash"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tb_ListCart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_ListCartMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tb_ListCart);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                .addContainerGap())
        );

        bttDelete.setText("Delete the product");
        bttDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttDeleteActionPerformed(evt);
            }
        });

        bttPay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bttPay.setForeground(new java.awt.Color(255, 0, 0));
        bttPay.setText("Pay");
        bttPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttPayActionPerformed(evt);
            }
        });

        lb_sun.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_sun.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_sun.setText("Cash:0 VND");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Invoice", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(51, 51, 255))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Bill:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Min code:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Cashier:");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Customer", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(0, 0, 255))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Min code:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Name:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Point:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Bonus:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Point");

        lb_point.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_point.setText("0");

        txt_minCodeC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_minCodeCKeyReleased(evt);
            }
        });

        txt_name.setEnabled(false);

        txt_point.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(61, 61, 61)
                        .addComponent(txt_name, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(66, 66, 66)
                        .addComponent(txt_point, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(lb_point))
                            .addComponent(jLabel6))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_minCodeC)
                            .addComponent(jLabel12))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txt_minCodeC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_point, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(lb_point))
                .addGap(24, 24, 24))
        );

        txt_bill.setEnabled(false);

        txt_cashier.setEnabled(false);

        txt_minCodeE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_minCodeEKeyReleased(evt);
            }
        });

        bttnewInvoice.setText("New invoice");
        bttnewInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnewInvoiceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(58, 58, 58)
                                .addComponent(txt_bill))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(10, 10, 10)
                                .addComponent(txt_minCodeE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(24, 24, 24)
                                .addComponent(txt_cashier)))
                        .addContainerGap())
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bttnewInvoice)
                .addGap(113, 113, 113))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_bill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_cashier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_minCodeE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bttnewInvoice)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(cm_Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bttSearch))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(bttDelete))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lb_sun, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(bttPay, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(cm_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bttSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bttDelete)
                        .addGap(18, 18, 18)
                        .addComponent(lb_sun)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bttPay, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttSearchActionPerformed
        // TODO add your handling code here:

       

    }//GEN-LAST:event_bttSearchActionPerformed

    private void tb_ListProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_ListProductMouseClicked
        // TODO add your handling code here:
     

    }//GEN-LAST:event_tb_ListProductMouseClicked

    private void tb_ListCartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_ListCartMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tb_ListCartMouseClicked

    private void bttBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttBuyActionPerformed
        // TODO add your handling code here:      
         int rowCount=tb_ListCart.getRowCount();
         int index=tb_ListProduct.getSelectedRow();
         if(rowCount==0)
         {         
                String row[]= new String[5];
                row[0]=tb_ListProduct.getValueAt(index, 0).toString();
                row[1]=tb_ListProduct.getValueAt(index, 1).toString();
                row[2]=tb_ListProduct.getValueAt(index, 2).toString() ;
                row[3]=txt_weight.getText();
                float cash=Float.valueOf(txt_weight.getText())*Float.valueOf(tb_ListProduct.getValueAt(index, 2).toString());
                row[4]=String.valueOf(cash);
                 DefaultTableModel model = new DefaultTableModel(); 
                model = (DefaultTableModel) tb_ListCart.getModel(); 
                model.addRow(row);
         }
         else
         {
             if(Check_Product(tb_ListProduct.getValueAt(index, 0).toString())==true)
             {
                for(int i=0;i<rowCount;i++)
                {
                    if(tb_ListCart.getValueAt(i,0).toString().compareTo(tb_ListProduct.getValueAt(index, 0).toString())==0)
                    {
                        
                        float  weight=Float.valueOf(txt_weight.getText().toString())+ Float.valueOf(tb_ListCart.getValueAt(i,3).toString());
                        float cash=weight*Float.valueOf(tb_ListCart.getValueAt(i,2).toString());
                        tb_ListCart.setValueAt(String.valueOf(weight), i, 3);
                        tb_ListCart.setValueAt(String.valueOf(cash), i, 4);
                    }
                }
             }
             else{
                    String row[]= new String[5];
                    row[0]=tb_ListProduct.getValueAt(index, 0).toString();
                    row[1]=tb_ListProduct.getValueAt(index, 1).toString();
                    row[2]=tb_ListProduct.getValueAt(index, 2).toString() ;
                    row[3]=txt_weight.getText();
                    float cash=Float.valueOf(txt_weight.getText())*Float.valueOf(tb_ListProduct.getValueAt(index, 2).toString());
                    row[4]=String.valueOf(cash);
                    DefaultTableModel model = new DefaultTableModel(); 
                    model = (DefaultTableModel) tb_ListCart.getModel(); 
                    model.addRow(row);
             }
         } 
         lb_sun.setText("Cash:"+Sum()+" VND");
         lb_point.setText(String.valueOf(Bonus()));
         txt_weight.setText("");
    }//GEN-LAST:event_bttBuyActionPerformed

    private void bttDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttDeleteActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = new DefaultTableModel(); 
            model = (DefaultTableModel) tb_ListCart.getModel();    
            int row[] = tb_ListCart.getSelectedRows(); 
            for (int i = 0; i < row.length; i++) { 
                model.removeRow(row[i]); 
            } 
             lb_sun.setText("Cash:"+Sum()+" VND");
             lb_point.setText(String.valueOf(Bonus()));
    }//GEN-LAST:event_bttDeleteActionPerformed

    private void bttnewInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnewInvoiceActionPerformed
        // TODO add your handling code here:
        txt_bill.setText(invoice_Controller.Auto_Increment_Mincode());
        
    }//GEN-LAST:event_bttnewInvoiceActionPerformed

    private void txt_minCodeCKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_minCodeCKeyReleased
        // TODO add your handling code here:
         ResultSet rs = null;
        rs=customer_Controller.Search_Mincode(txt_minCodeC.getText().toString());
         try {
                 while (rs.next()) {
                    
                   txt_name.setText(rs.getString(2)); 
                   txt_point.setText(rs.getString(7));
              }
             
            
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }
        
    }//GEN-LAST:event_txt_minCodeCKeyReleased

    private void txt_minCodeEKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_minCodeEKeyReleased
        // TODO add your handling code here:
         ResultSet rs = null;
        rs=employee_Controller.Search_Mincode_cashier(txt_minCodeE.getText().toString());
         try {
                 while (rs.next()) {
                    
                   txt_cashier.setText(rs.getString(2)); 
                  
              }
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }
        
    }//GEN-LAST:event_txt_minCodeEKeyReleased

    private void bttPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttPayActionPerformed
        // TODO add your handling code here:
        
        
       
        invoice_Model.setMincodeI(txt_bill.getText());
        invoice_Model.setMincodeE("NV"+txt_minCodeE.getText());
        invoice_Model.setMincodeC("KH"+txt_minCodeC.getText());
        invoice_Model.setDay(String.valueOf(java.time.LocalDate.now()));
        invoice_Model.setCash(Sum());
        
        invoice_details_Model.setMincdeI(txt_bill.getText());
        
         if(txt_minCodeC.getText().compareTo("")==0)
         {
             invoice_Controller.Add_Invoice_Not_Customer(invoice_Model);
         }
         else
         {
              invoice_Controller.Add_Invoice(invoice_Model);
              customer_Model.setMincode("KH"+txt_minCodeC.getText());
              int point=Bonus()+Integer.valueOf(txt_point.getText());
              customer_Model.setPoints(point);
              customer_Controller.Update_Point(customer_Model);
              
         }
            
      
        
        int rowCount=tb_ListCart.getRowCount();
        for(int i=0;i<rowCount;i++)
        {
               invoice_details_Model.setMincodeP(tb_ListCart.getValueAt(i, 0).toString());
               invoice_details_Model.setPrice(Float.valueOf(tb_ListCart.getValueAt(i, 2).toString()));
               invoice_details_Model.setWeight(Float.valueOf(tb_ListCart.getValueAt(i, 3).toString()));
               invoice_details_Model.setCash(Float.valueOf(tb_ListCart.getValueAt(i, 4).toString()));
               
               invoice_details_Controller.Add_Invoice_details(invoice_details_Model);
        }
        
         JOptionPane.showMessageDialog(null,"Successfully Pay!");
        
    }//GEN-LAST:event_bttPayActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttBuy;
    private javax.swing.JButton bttDelete;
    private javax.swing.JButton bttPay;
    private javax.swing.JButton bttSearch;
    private javax.swing.JButton bttnewInvoice;
    private javax.swing.JComboBox cm_Search;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lb_point;
    private javax.swing.JLabel lb_sun;
    private javax.swing.JTable tb_ListCart;
    private javax.swing.JTable tb_ListProduct;
    private javax.swing.JTextField txt_Search;
    private javax.swing.JTextField txt_bill;
    private javax.swing.JTextField txt_cashier;
    private javax.swing.JTextField txt_minCodeC;
    private javax.swing.JTextField txt_minCodeE;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_point;
    private javax.swing.JTextField txt_weight;
    // End of variables declaration//GEN-END:variables
}
